#!/bin/bash

## Description: Perform first time site-install and npm install/builds
## Usage: init
## Example: ddev init
drush site:install --account-name=admin --account-pass=admin -y
drush pm:install experience_builder media media_library
drush pm:install components
cd /var/www/html/src/web/modules/contrib/experience_builder/ui && npm i && npm run build
cd /var/www/html/src/web/themes/contrib/demo_design_system && npm i && npm run build
cd /var/www/html/src/web/themes/contrib/demo_design_system/starshot_demo && npm i && npm run build
drush theme:enable civictheme -y
drush theme:enable starshot_demo -y
drush config:set system.theme default starshot_demo -y
# Clear the cache
drush cr